gold/gamification/gamification/badges/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *

from badges import views

urlpatterns = patterns('',
    url(r'^$', views.overview, name="badges_overview"),
    url(r'^(?P<slug>[A-Za-z0-9_-]+)/$', views.detail, name="badge_detail"),
    )

gold/gamification/gamification/urls.py
# -*- coding: utf-8 -*-

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, as long as
# any reuse or further development of the software attributes the
# National Geospatial-Intelligence Agency (NGA) authorship as follows:
# 'This software (gamification-server)
# is provided to the public as a courtesy of the National
# Geospatial-Intelligence Agency.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, ListView

from django.contrib import admin
admin.autodiscover()
from gamification.core.models import Project
from gamification.core.views import *
from gamification.events.views import handle_event, assign_badge

urlpatterns = patterns("",
    url(r"^gamification/$", TemplateView.as_view(template_name="core/index.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^users/?$", UserView.as_view(template_name='core/users.html'), name='user_list'),
    url(r"^users/(?P<username>[\w.@]+)/", include("gamification.core.urls")),
    url(r"^projects/$", master_project_list),

    url(r"^projects/all/", MasterProjectListView.as_view(template_name='core/masterprojects_list.html'), name='master-project-list'),
    url(r"^projects/(?P<projectname>[\w ]+)/?$", ProjectListView.as_view(template_name='core/projects_list.html'), name='project-list'),
    url(r"^projects/(?P<projectname>[\w ]+)/admin/?$", ProjectAdminListView.as_view(template_name='core/project_admin.html'), name='project-admin'),

    url(r"^projects/(?P<projectname>[\w ]+)/(?P<phrase>\w+)/?$", ProjectListView.as_view(template_name='core/projects_list.html'), name='project-list'),

    url(r"^projects/(?P<projectname>[\w ]+)/leaders/?$", project_all_badgeleaders_view),
    # url(r"^projects/(?P<projectname>\w+)/badges/?$", BadgeListView.as_view(template_name='core/badge_list.html'), name='badge-list'),
    url(r"^projects/(?P<projectname>[\w ]+)/badges/(?P<badgename>\w+)/leaders/?$", project_badgeleaders_view),
    url(r'^badges/?$', MasterBadgeListView.as_view(template_name='core/master_badge_list.html'), name='master-badge-list'),
    url(r'^users/(?P<username>[\w.@]+)/projects/(?P<projectname>[\w ]+)/event/?$', handle_event),
    url(r'^users/(?P<username>[\w.@]+)/assign_badge/(?P<badge>[\w ]+)?$', assign_badge),
    url(r'^users/(?P<username>[\w.@]+)/create/?$', create_new_user),
    url(r'^$', MasterBadgeListView.as_view(template_name="core/index.html"), name="home"),
    url(r'^users/(?P<username>[\w .-@])/projects/(?P<projectname>\w+)/event/?$', handle_event),
    url(r'^users/(?P<username>[\w .-@])/assign_badge/(?P<badge>\w+)?$', assign_badge),
    url(r'^users/(?P<username>[\w .-@])/create/?$', create_new_user),
    url(r'^$', TemplateView.as_view(template_name="core/index.html"), name="home"),

    # Open Badges interoperability. Define an Issuer
    url(r'^projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/issuer/?$', \
        get_issuer, name="openbadges_issuer"),

    # and a way to retrieve a badge's image
    url(r'^projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/image/?$', \
        get_image, name="openbadges_image"),

    # a badge's metadata
    url(r'^projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/metadata/?$', \
        get_metadata, name="openbadges_metadata"),
        
    # a badge's criteria
    url(r'projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/criteria/?$', \
        get_criteria, name='openbadges_criteria'),
        
    # badge instance metadata
    url(r'projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/users/(?P<username>[\w .-@])/award/?$', \
        get_badge_award, name='openbadges_award'),
)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gold/gamification/gamification/badges/models.py
# -*- coding: utf-8 -*-

from datetime import datetime

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings

from singleton_models.models import SingletonModel
#from gamification.core.models import Project

from signals import badge_awarded
from managers import BadgeManager

if hasattr(settings, 'BADGE_LEVEL_CHOICES'):
    LEVEL_CHOICES = settings.BADGE_LEVEL_CHOICES
else:
    LEVEL_CHOICES = (
        ("1", "Bronze"),
        ("2", "Silver"),
        ("3", "Gold"),
        ("4", "Diamond"),
    )

class Badge(models.Model):
    name = models.CharField(max_length=255)
    level = models.CharField(max_length=1, choices=LEVEL_CHOICES)    
    icon = models.ImageField(upload_to='badge_images', default='', null=True, blank=True )
    value = 1
    
    objects = BadgeManager()
    
    @property
    def meta_badge(self):
        from utils import registered_badges
        return registered_badges[self.id]
    
    @property
    def title(self):
        return self.name
    
    @property
    def description(self):
        return self.meta_badge.description
    
    def __unicode__(self):
        return u"%s" % self.name
    
    def get_absolute_url(self):
        return reverse('badge_detail', kwargs={'slug': self.id})

    class Meta:
        verbose_name_plural = "Badge Templates"


class ProjectBadge(models.Model):
    project = models.ForeignKey('core.Project')
    badge = models.ForeignKey('Badge')
    user = models.ManyToManyField(User, related_name="badges", through='ProjectBadgeToUser')
    name = models.CharField(max_length=255)
    description = models.TextField()
    created = models.DateTimeField(default=datetime.now)
    awardLevel = models.IntegerField(default=1)
    multipleAwards = models.BooleanField(default=True)
    tags = models.CharField(max_length=400, default='', null=True, blank=True, help_text='Tags associated with this badge. Use a few small words separated by commas.')

    @property
    def meta_badge(self):
        from utils import registered_badges
        return registered_badges[self.id]

    def award_to(self, user):
        #has_badge = self in user.badges.all()
        #if self.meta_badge.one_time_only and has_badge:
        #    return False
        
        ProjectBadgeToUser.objects.create(projectbadge=self, user=user)
                
        #badge_awarded.send(sender=self.meta_badge, user=user, badge=self)
        
        #Grr... deprecated for Django 1.4+
        #message_template = "You just got the %s Badge!"
        #user.message.success(message = message_template % self.title)
        
        return ProjectBadgeToUser.objects.filter(projectbadge=self, user=user).count()

    def number_awarded(self, user_or_qs=None):
        """
        Gives the number awarded total. Pass in an argument to
        get the number per user, or per queryset.
        """
        kwargs = {'badge':self}
        if user_or_qs is None:
            pass
        elif isinstance(user_or_qs, User):
            kwargs.update(dict(user=user_or_qs))
        else:
            kwargs.update(dict(user__in=user_or_qs))
        return ProjectBadgeToUser.objects.filter(**kwargs).count()

    def __str__(self):
        return self.name

class ProjectBadgeToUser(models.Model):
    projectbadge = models.ForeignKey(ProjectBadge)
    user = models.ForeignKey(User)
    created = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name_plural = "Awarded Badges"

class BadgeSettings(models.Model):
    awardLevel = models.IntegerField(default=1)
    multipleAwards = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Badge Settings"

gold/gamification/gamification/badges/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from models import Badge

def overview(request, extra_context={}):
    badges = Badge.objects.active().order_by("level")
    
    context = locals()
    context.update(extra_context)
    return render_to_response("badges/overview.html", context, context_instance=RequestContext(request))

def detail(request, slug, extra_context={}):
    badge = get_object_or_404(Badge, id=slug)
    users = badge.user.all()
    
    context = locals()
    context.update(extra_context)
    return render_to_response("badges/detail.html", context, context_instance=RequestContext(request))

gold/gamification/gamification/badges/templates/badges/badge.html
{% comment %}
	This is the html for displaying an individual badge on the site. It expects that
	you will pass it a badge object called "badge".

	Here is an example:
	<div class="badges">
		{% for badge in user_profile.user.badges.all %}
			{% include "badges/badge.html" %}
		{% endfor %}
	</div>

{% endcomment %}

<a href="{{ badge.get_absolute_url }}" title="{{ badge.title }} ({{ badge.get_level_display }}): {{ badge.description }}">
	<span class="level_{{ badge.level}} metal"><img src="{{ badge.icon.url }}"></span> {{ badge.title }}
</a>

gold/gamification/gamification/badges/templates/badges/badges_display.html
{% comment %}
	This template is for displaying the badges a user has earned next to their name. It 
	expects that you will pass it a list of badge objects called badges.

	Here is an easy way to do that:

	{% with badges as post.user.badges %}
		{% include "badges/badges_display.html %}
	{% endwith %}

{% endcomment %}



{% load badges_tags %}
<span class="badge">
<!-- span>{{request.user.get_profile.score}}</span -->
{% if request.user %}
{% for level in request.user|badge_count %}
	{% if level.count %}
		<span title="{{level.count}} {{level.badge__level|level_title}} badge{{level.count|pluralize}}"><span class="level_{{level.badge__level}} metal"><img src="{{ level.badge__level|level_icon }}"></span>{{level.count}} &nbsp</span>
	{% endif %}
{% endfor %}
{% endif %}
</span>

gold/gamification/gamification/badges/templates/badges/detail.html
{% extends "badges/overview.html" %}
{% load badges_tags %}
{% load humanize %}

{% block body %}
<div id="badges_tank">
	<h1>{% block head_title %}Badge: {{ badge.title }}{% endblock %}</h1>
    <p class="info_blurb">{{ badge.description }}</p>
	<ul class="users">
		{% for u in users %}
			<li><a href='{{ u.get_absolute_url }}'>{{ u.username }}</a></li>
		{% empty %}
			<li>Nobody has earned this badge!</li>
		{% endfor %}
    </ul>
</div>
{% endblock %}

gold/gamification/gamification/badges/templates/badges/overview.html
{% extends "site_base.html" %}
{% load badges_tags %}
{% load humanize %}

{% block container %}
<div id="badges_tank">
	<h1>{% block head_title %}Badges{% endblock %}</h1>
	<p class="info_blurb">Contribute to one or more analyst tasks to earn points and badges.  Here is a list of the badges, and how many people have earned each one.</p>
	<p class="info_blurb">Badges are fun! They're just little reminders that <strong>you are awesome</strong> <span class="faces">☺</span></p>
	<table class="badges">
		{% for badge in badges %}
		<tr class="{% cycle 'highlighted' '' %}">
			<td class="checkmarks">
				{% if badge|is_in:request.user.badges.all %}<span title="You have earned this badge">✔</span>{% endif %}&nbsp;
			</td>
			<td class="badge">
				{% include "badges/badge.html" %}
				× {{ badge.user.count|intcomma }}
			</td>
			<td class="badge_description">{{ badge.description }}</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}