gold/gamification/gamification/core/urls.py
# -*- coding: utf-8 -*-

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, as long as
# any reuse or further development of the software attributes the
# National Geospatial-Intelligence Agency (NGA) authorship as follows:
# 'This software (gamification-server)
# is provided to the public as a courtesy of the National
# Geospatial-Intelligence Agency.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from django.conf.urls import patterns, url, include
from views import *


urlpatterns = patterns('',

    # PROJECTS

    url(r'^projects/(?P<projectname>\w+)/award/?$', 'gamification.core.views.award', name='award'),
    url(r'^projects/(?P<projectname>\w+)/points/?$', user_project_points_list),
    url(r'^projects/(?P<projectname>\w+)/points/?format=(?P<rendertype>\w+)?$', user_project_points_list),
    url(r'^projects/(?P<projectname>\w+)/total/?$', user_points),
    url(r'^projects/(?P<projectname>[\w,]+)/badges/?$', user_project_badges_list),
    url(r'^projects/(?P<projectname>[\w,]+)/badges/?format=(?P<rendertype>\w+)?$', user_project_badges_list),

    # POINTS
    url(r'^points/?$', user_points_list),

)

gold/gamification/gamification/urls.py
# -*- coding: utf-8 -*-

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, as long as
# any reuse or further development of the software attributes the
# National Geospatial-Intelligence Agency (NGA) authorship as follows:
# 'This software (gamification-server)
# is provided to the public as a courtesy of the National
# Geospatial-Intelligence Agency.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, ListView

from django.contrib import admin
admin.autodiscover()
from gamification.core.models import Project
from gamification.core.views import *
from gamification.events.views import handle_event, assign_badge

urlpatterns = patterns("",
    url(r"^gamification/$", TemplateView.as_view(template_name="core/index.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^users/?$", UserView.as_view(template_name='core/users.html'), name='user_list'),
    url(r"^users/(?P<username>[\w.@]+)/", include("gamification.core.urls")),
    url(r"^projects/$", master_project_list),

    url(r"^projects/all/", MasterProjectListView.as_view(template_name='core/masterprojects_list.html'), name='master-project-list'),
    url(r"^projects/(?P<projectname>[\w ]+)/?$", ProjectListView.as_view(template_name='core/projects_list.html'), name='project-list'),
    url(r"^projects/(?P<projectname>[\w ]+)/admin/?$", ProjectAdminListView.as_view(template_name='core/project_admin.html'), name='project-admin'),

    url(r"^projects/(?P<projectname>[\w ]+)/(?P<phrase>\w+)/?$", ProjectListView.as_view(template_name='core/projects_list.html'), name='project-list'),

    url(r"^projects/(?P<projectname>[\w ]+)/leaders/?$", project_all_badgeleaders_view),
    # url(r"^projects/(?P<projectname>\w+)/badges/?$", BadgeListView.as_view(template_name='core/badge_list.html'), name='badge-list'),
    url(r"^projects/(?P<projectname>[\w ]+)/badges/(?P<badgename>\w+)/leaders/?$", project_badgeleaders_view),
    url(r'^badges/?$', MasterBadgeListView.as_view(template_name='core/master_badge_list.html'), name='master-badge-list'),
    url(r'^users/(?P<username>[\w.@]+)/projects/(?P<projectname>[\w ]+)/event/?$', handle_event),
    url(r'^users/(?P<username>[\w.@]+)/assign_badge/(?P<badge>[\w ]+)?$', assign_badge),
    url(r'^users/(?P<username>[\w.@]+)/create/?$', create_new_user),
    url(r'^$', MasterBadgeListView.as_view(template_name="core/index.html"), name="home"),
    url(r'^users/(?P<username>[\w .-@])/projects/(?P<projectname>\w+)/event/?$', handle_event),
    url(r'^users/(?P<username>[\w .-@])/assign_badge/(?P<badge>\w+)?$', assign_badge),
    url(r'^users/(?P<username>[\w .-@])/create/?$', create_new_user),
    url(r'^$', TemplateView.as_view(template_name="core/index.html"), name="home"),

    # Open Badges interoperability. Define an Issuer
    url(r'^projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/issuer/?$', \
        get_issuer, name="openbadges_issuer"),

    # and a way to retrieve a badge's image
    url(r'^projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/image/?$', \
        get_image, name="openbadges_image"),

    # a badge's metadata
    url(r'^projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/metadata/?$', \
        get_metadata, name="openbadges_metadata"),
        
    # a badge's criteria
    url(r'projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/criteria/?$', \
        get_criteria, name='openbadges_criteria'),
        
    # badge instance metadata
    url(r'projects/(?P<projectname>\w+)/badges/(?P<badgename>\w+)/users/(?P<username>[\w .-@])/award/?$', \
        get_badge_award, name='openbadges_award'),
)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gold/gamification/gamification/core/models.py
# -*- coding: utf-8 -*-

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, as long as
# any reuse or further development of the software attributes the
# National Geospatial-Intelligence Agency (NGA) authorship as follows:
# 'This software (gamification-server)
# is provided to the public as a courtesy of the National
# Geospatial-Intelligence Agency.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import json
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.datastructures import SortedDict
from django.db.models.signals import post_save
from django.db import models
from gamification.badges.models import ProjectBadge, ProjectBadgeToUser
from jsonfield import JSONField
from mptt.models import MPTTModel, TreeForeignKey


TRUE_FALSE = [(0, 'False'), (1, 'True')]


class ProjectBase(models.Model):
    """
    A generic model for GeoQ objects.
    """

    active = models.BooleanField(default=True, help_text='If checked, this project will be listed in the active list.')
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, help_text='Name of the project.')
    description = models.TextField(help_text='Details of this project that will be listed on the viewing page.')
    updated_at = models.DateTimeField(auto_now=True)
    url = models.TextField(help_text='Project Information URL', null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True
        ordering = ('-created_at',)


class Team(MPTTModel):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    members = models.ManyToManyField(User, null=True, blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')
    order = models.IntegerField(default=0, null=True, blank=True, help_text='Optionally specify the order teams should appear. Lower numbers appear sooner. By default, teams appear in the order they were created.')
    date_created = models.DateTimeField(auto_now_add=True)

    background_color = models.CharField(max_length=50, null=True, blank=True, help_text='Optional - Color to use for background of all team badges')
    icon = models.ImageField(upload_to='badge_images', null=True, blank=True, help_text='Optional - Image to show next to team names')

    def __str__(self):
        return "%s (%s)" % (self.name, str(len(self.members.all())))

    def get_all_users(self, include_self=True):
        u = []
        if include_self:
            u += self.members.all()
        for team in self.get_descendants():
            u += team.members.all()

        return u

    class Meta:
        ordering = ['-order', '-date_created', 'id']

    class MPTTMeta:
        order_insertion_by = ['name']


class Project(ProjectBase):
    """
    Top-level organizational object.
    """

    THEMES = (
        ("", "None"),
        ("camping", "Camping"),
        ("camping2", "Camping Theme 2"),
        ("map", "Geospatial"),
    )

    private = models.BooleanField(default=False, help_text='If checked, hide this project from the list of projects and public badge APIs.')
    supervisors = models.ManyToManyField(User, blank=True, null=True, related_name="supervisors", help_text='Anyone other than site administrators that can add badges and update the site')
    teams = models.ManyToManyField(Team, blank=True, null=True)
    viewing_pass_phrase = models.CharField(max_length=200, null=True, blank=True, help_text='Phrase that must be entered to view this page.')
    project_closing_date = models.DateTimeField(null=True, blank=True, help_text='Date that project "closes" with countdown shown on project page. Badges can still be added after this.')
    visual_theme = models.CharField(max_length=20, default="none", choices=THEMES, help_text='Visual Theme used to style the project page')
    background_image = models.ImageField(upload_to='badge_images', null=True, blank=True, help_text='Optional - Override theme background with this image')

    properties = JSONField(null=True, blank=True, help_text='JSON key/value pairs associated with this object, e.g. {"badges_mode":"blue"}')

    query_token = models.CharField(max_length=200, null=True, blank=True, help_text='Token that must be entered by any server requesting data - not implemented yet.')
    allowed_api_hosts = models.TextField(null=True, blank=True, help_text='Comma-separated list of hosts (IPs or Hostnames) that can access this project via data requests - not implemented yet')

    @property
    def user_count(self):
        return User.objects.filter(projectbadgetouser__projectbadge__project=self).distinct().count()

    @property
    def badge_count(self):
        return ProjectBadgeToUser.objects.filter(projectbadge__project=self).count()

    def get_absolute_url(self):
        return reverse('project-list', args=[self.name])

class Points(models.Model):
    user = models.ForeignKey(User)
    projectbadge = models.ForeignKey(ProjectBadge)
    value = models.IntegerField(default=0)
    date_awarded = models.DateTimeField('date awarded',auto_now=True)
    description = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('points-list', args=[self.id])

    class Meta:
        verbose_name_plural = "Points"


class UserProfile(models.Model):
    """ from http://stackoverflow.com/questions/44109/extending-the-user-model-with-custom-fields-in-django; this is one mechanism for adding extra details (currently score for badges) to the User model """
    defaultScore = 1
    user = models.OneToOneField(User)
    score = models.IntegerField(default=defaultScore)

    def __str__(self):
          return "%s's profile" % self.user

def create_user_profile(sender, instance, created, **kwargs):
    if created:
       profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile, sender=User)

import sys
if not 'syncdb' in sys.argv[1:2] and not 'migrate' in sys.argv[1:2]:
    from meta_badges import *

gold/gamification/gamification/core/forms.py
# This technical data was produced for the U. S. Government under Contract No. W15P7T-13-C-F600, and
# is subject to the Rights in Technical Data-Noncommercial Items clause at DFARS 252.227-7013 (FEB 2012)

from django import forms
from django.contrib.auth.models import User
from gamification.badges.models import ProjectBadge

class AwardForm(forms.Form):

    award_id = forms.ModelChoiceField(label=(u'Award'),
                                        queryset=ProjectBadge.objects.all(),
                                        required=True)
    points = forms.ChoiceField(label=(u'Points to Award'),
                               widget=forms.Select(),
                               choices=([('1','1'),('5','5'),('10','10'),('20','20'),('50','50'),]),
                               required=True)
    comment = forms.CharField(label=(u'Comment'),
                              max_length=255)

gold/gamification/gamification/core/templates/core/award.html
{% extends 'core/base.html' %}

{% block content %}
<h1>Submit Award</h1>
        <br/>
<div class="row">
    <div class="col-md-10">
<form role="form" class="form-horizontal" action="" method="post" id="badge_award">
    <fieldset>
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            <div class="row">
                <div class="col-sm-offset-1 col-sm-10">
                {{ field.label_tag }}
                    </div>
            </div>

            <div class="col-sm-offset-1 col-sm-10">
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" value="Submit" />
        </div>
    </div>

    </fieldset>
</form>
        </div>
    </div>
{% endblock %}

gold/gamification/gamification/core/templates/core/badge_list.html
{% extends "core/base.html" %}
{% load staticfiles %}
{% block content %}
{% block heading %}

<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <div class="page-header">
            <h2>Badges for project {{ project_name }}</h2>
        </div>
    </div>
</div>


{% endblock %}
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Icon</th>
                    <th>Description</th>
                    <th>Points Worth</th>
                    <th>Can win Multiple?</th>
                </tr>
                </thead>
                <tbody>
                {% for badge in object_list %}
                <tr>
                    <td>
                        {{ badge.name }}
                    </td>
                    <td>
                        {% with badge_icon=badge.badge__icon %}
                        {% static badge_icon as badge_url %}
                        <img src="{{ badge_url }}">
                        {% endwith %}
                    </td>
                    <td>
                        {{ badge.description }}
                    </td>
                    <td>
                        {{ badge.awardLevel }}
                    </td>
                    <td>
                        {{ badge.multipleAwards }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

gold/gamification/gamification/core/templates/core/index.html
{% extends "core/base.html" %}
{% block title %}Gamification Server{% endblock %}
{% load staticfiles %}
{% block content %}

<div class="row">
    <div class="col-lg-10">
        <div class="jumbotron">
            <h1>Gamification Server</h1>
            <p>The Gamification Server is a management tool that allows other web pages, apps, or tools to
                utilize "<a href="http://en.wikipedia.org/wiki/Gamification" target=_new">Gamification</a>" concepts.  These ideas
                have been found to help engage with some users and encourage teamwork.</p>

            <p>Gamification-server provides a framework for providing awards to users or teams and can be operated either
                standalone or integrated with other web-based applications. Based on the notion of badges used within other
                gamification systems, gamification-server also provides a customizable web interface for displaying badges as
                well as a configurable rules engine to translate actions performed by users into awards. User awards can be
                exported into an Open Badges Backpack, allowing users to present expertise gained within other social
                frameworks or applications. The gamification-server is implemented as a django python web service and
                associated web application.</p>

            <p>The source code for this server is Open Source and currently available on <a href="https://github.com/ngageoint/gamification-server" target="_new">GitHub</a>
                and available for anyone to use and improve upon. <b>We encourage your participation and want to hear your ideas!</b>
                This is a prototype concept used to integrate tools and test out concepts. Interfaces are available either
                through this web interface or through a REST-based API calls.
            </p>
        </div>

        <div>
            <h4>Some of the Badges in various projects</h4>
            {% for badge in object_list %}
                {% with badge_icon=badge.badge__icon %}
                {% static badge_icon as badge_url %}
                <img src="{{ badge_url }}" style="max-width: 90px" title="{{ badge.name }}">
                {% endwith %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

gold/gamification/gamification/core/templates/core/projects_list.html
{% extends 'core/base.html' %}
{% load mptt_tags %}
{% load teams %}
{% block title %}{{ project.name|capfirst }} - Gamification Server{% endblock %}

{% block header_title %}
    <div id="header_title">
        <h1>{{ project.name|capfirst }}</h1>
        <b>{{ project.description|linebreaks|capfirst|default:"Gamification Project" }}</b>
    </div>
{% endblock %}

{% block content %}

{% if project.viewing_pass_phrase and project.viewing_pass_phrase != code %}
    <form method="get" id="phrase_form" action="">{% csrf_token %}
        This page is protected from public viewing. Please enter entry code: <input type="text" id="entry_code" />
        <input type="button" id="enter_phrase" value="Reveal Results"/>
    </form>
    <script>
        var text_input = document.getElementById('entry_code');
        text_input.focus ();
        text_input.select ();
        $(document).ready(function(){
            $('#enter_phrase').click(function(){
                var phrase = $('#entry_code').val();
                document.location.href = "{{ project.get_absolute_url }}/" + phrase;
            });

            $('#entry_code').on('input',function(){
                var phrase = $('#entry_code').val();
                var $form = $('#phrase_form');
                $form.attr('action',"{{ project.get_absolute_url }}/" + phrase);
            });

        });
    </script>
{% else %}

    <script src="{{ STATIC_URL }}js/maths.js"></script>
    {% for file in theme_files_js %}
    <script src="{{ STATIC_URL }}themes/{{ project.visual_theme }}/{{ file }}"></script>
    {% endfor %}

    {% if project.project_closing_date %}
    <script src="{{ STATIC_URL }}js/TimeCircles/TimeCircles.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}js/TimeCircles/TimeCircles.css">
    {%  endif %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project_list.css">

    {% for file in theme_files_css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}themes/{{ project.visual_theme }}/{{ file }}">
    {% endfor %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/ui.fancytree.css">
    <script src="{{ STATIC_URL }}js/jquery-ui.custom.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.fancytree.js"></script>

    <style>
        {%  if project.background_image %}
        html {
            background: url({{ STATIC_URL }}{{ project.background_image }}) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        {% endif %}
    </style>
    <script>
        var project_info = {};
        project_info.closing_date = '{{ project.project_closing_date|default:"" }}';
        project_info.name = '{{ project.name|default:"" }}';
        project_info.id = '{{ project.id }}';
        project_info.properties = {{ properties_json|safe }};
        {% autoescape off %}
        project_info.badge_json = {{ badge_awards_json|default:"''" }};
        project_info.theme_files = {{ theme_files|safe|default:"''" }};
        project_info.team_members = {{ nodes|teamify }};
        {% endautoescape %}

        $(document).ready(function(){
            $('.dtg').each(function(){
                var $item = $(this);
                var dtg = $item.text();
                var time = moment(dtg);
                if (time.isValid()){
                    var newtime = time.calendar();
                    $item.text('Awarded '+newtime);
                }
            });

            // add members to the teams displayed in team board
            _.each($("#tree li"), function(team_node) {
                var teamid = team_node.id;
                if (project_info.team_members[teamid].length > 0) {
                    // add members to <ul> of that list if it exists, or create one if it doesn't
                    var ul_node = $("#"+teamid + " ul");
                    if (! ul_node.length) {
                        $("#" + teamid).append("<ul>");
                    }

                    _.each(project_info.team_members[teamid], function (member) {
                        ul_node = $("#"+teamid + " ul");
                        ul_node.prepend("<li>" + member['name'] + " [" + member['points'] + "]</li>");
                    });
                }

            });

            {% if project.project_closing_date %}
            $(".countdown_clock").TimeCircles();
            {% endif %}

            //Highlight the first tab
            $('.nav-tabs li').first().addClass('active');
            $('.tab-content > .tab-pane').first().addClass('active');


            //Count number of teams, and if any add displays
            var _teams = _.groupBy(project_info.badge_json,function(b){return b[3]});
            var iname_count = 0; for (iname in _teams) {if (iname) iname_count++};
            if (iname_count > 1) {
                var $leaderboard = $('#leader_board_table');
                _.each(_teams,function(team,team_name){
                    var team_points = 0;
                    var team_badges = 0;
                    _.each(team,function(member){
                        team_points+=member[2];
                        team_badges+=member[1].length;
                    });
                    if (!team_name && project_info.properties.showEmptyTeams) {
                        if (_.isString(project_info.properties.showEmptyTeams)) {
                            team_name = project_info.properties.showEmptyTeams;
                        } else {
                            team_name = "Unaffiliated";
                        }
                    }

                    if (team_name) {
                        $('<div>')
                            .css({display:'inline-block',padding:'6px',margin:'4px',textAlign:'center',width:'200px',height:'120px',border:'2px solid black',borderRadius:'8px',backgroundColor:'lightblue',opacity:0.8})
                            .html("<h3>"+team_name+"</h3><h4>Points: "+team_points+"</h4><h4>Badges: "+team_badges+"</h4>")
                            .prependTo($leaderboard);
                    }
                });
            }


        });
    </script>

    <script>
        $(function(){
            // using default options
            $("#tree").fancytree();
        });

    </script>

    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li><a href="#team_board" data-toggle="tab">Team board</a></li>
        <li><a href="#leader_board" data-toggle="tab">Leader board</a></li>
        <li><a href="#badge_leaders" data-toggle="tab">Badge Leaders</a></li>
        <li><a href="#badge_list" data-toggle="tab">Badge List</a></li>
        {% if project.project_closing_date %}
        <li><a href="#data_graph" data-toggle="tab">Project Data</a></li>
        {%  endif %}
    </ul>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane" id="team_board">
            <div id="tree">
            {# -- Team Board -- #}
            {% for team,structure in nodes|tree_info %}
                {% if structure.new_level %}<ul>{% else %}</li>{% endif %}
                <li class="folder expanded" id="{{ team.name|slugify }}">

                {{ team.name }} [{{ team.points }}]

                {% for team.level in structure.closed_levels %}</li></ul>{% endfor %}
            {% endfor %}
            </div>
            <!-- div id="team_board_table">
                {% for team in badge_awards %}
                <div class="row">
                    <span style="width: 140px;"><b>{{ awardee|capfirst }}</b>
                        {% if team %}[{{ team.name }}]{% endif %}
                    </span>
                </div>
                {% endfor %}
            </div -->
        </div>
        <div class="tab-pane" id="leader_board">

            {# -- Leader Board -- #}
            <div id="leader_board_table">
                {% for awardee,badges,score,team in badge_awards %}
                <div class="row badge-row leader">
                    <span style="width: 140px;"><b>{{ awardee|capfirst }}</b>
                    {% if team %}[{{ team|capfirst }}]{% endif %}
                    </span>
                    <span><b>{{ score }}: </b></span>
                    {% for badge in badges %}
                        <img src="/static/{{ badge.icon }}" title="{{ badge.badge }}"/>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>

        </div>
        <div class="tab-pane" id="badge_leaders">

                {# -- Top Badge Winners -- #}
                {% for top_badge in top_n_badges|dictsortreversed:"awardLevel" %}
                <div class="row badge-row">
                    <span style="width: 100px;">
                        <img src="/static/{{  top_badge.badge__icon|default:'badge_icons/default.png' }}" width="90"/>
                    </span>
                    <span style="width: 500px;">
                        <b>{{ top_badge.name|title }} ({{ top_badge.awardLevel }} point{{ top_badge.awardLevel|pluralize }})</b><br/>
                        <i>{{ top_badge.description|capfirst }}</i>
                    </span>
                    <span>
                        {% if not top_badge.leaders %}
                            <i>No badges assigned yet</i>
                        {% else %}
                            <h4>Top Badge Recipients:</h4>
                            {% for leader in top_badge.leaders %}
                                <li><b>{{ leader.user__username }} </b>: <i>(Received {{ leader.awarded }} time{{ leader.awarded|pluralize }})</i></li>
                            {% endfor %}
                        {% endif %}
                    </span>
                </div>
                {% endfor %}

        </div>
        <div class="tab-pane" id="badge_list">

                {# -- All Badge Recipients -- #}
                {% for awardee,badges,score,team in badge_awards %}
                <div class="row badge-row">
                    <span style="width: 100px;"><b>{{ awardee }}</b>
                    {% if team %}<br/>[{{ team|capfirst }}]{% endif %}
                    </span>
                    <span>
                        <b>{{ badges|length }} Badge{{ badges|pluralize }} - {{ score }} point{{ score|pluralize }}:</b>
                        {% for badge in badges %}
                            <li><img src="/static/{{ badge.icon }}" style="width: 20px"/> <span class="awardee"><b>{{ badge.badge|title }}</b></span>: {{ badge.points }} point{{ badge.points|pluralize }} - <span class="dtg">{{ badge.date }}</span></li>
                        {% endfor %}
                    </span>
                </div>
                {% endfor %}

        </div>

        {% if project.project_closing_date %}
        <div class="tab-pane" id="data_graph">
                {# -- Coundown clock -- #}
                <div style="font-size: 20px;font-weight: bold;">
                    Project closes in: <div class="countdown_clock" data-date="{{ project.project_closing_date|date:"Y-m-d" }} {{ project.project_closing_date|time:"H:i:s" }}" style="height:100px"></div>
                </div>
        </div>
        {% endif %}

    </div>

    {%  if admin %}
        <button type="button" class="btn btn-primary btn-sm" onclick="location.href='{{ project.get_absolute_url }}/admin'">Admin: Add Badges to Users</button>
    {%  endif %}

{% endif %}
{% endblock %}